In [5]:
# add .. to PYTHONPATH
import sys
sys.path.append("..")
%load_ext autoreload
%autoreload 2

from telemetry import Telemetry

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
t = Telemetry()
t.set_pandas_adapter()
t.set_filter({'session_id': 1719840630})
t.get_telemetry_df().head()

,result,table,_start,_stop,_time,CarModel,CurrentLap,GameName,SessionId,SessionTypeName,...,Rpms,SpeedMs,SteeringAngle,Throttle,TyreType,WorldPosition_x,WorldPosition_y,WorldPosition_z,Yaw,id
0,_result,0,2023-07-02 16:14:22.730341+00:00,2024-07-01 16:14:22.730341+00:00,2024-07-01 15:30:30.457458+00:00,Citroen Xsara Kit Car,0,Richard Burns Rally,1719840630,NewSession,...,1006.15900,0.0,-0.015686,0.000000,Dry Gravel,-231.150589,83.04983,-27.045351,-64.44776,1719840630-0
1,_result,1,2023-07-02 16:14:22.730341+00:00,2024-07-01 16:14:22.730341+00:00,2024-07-01 15:30:35.640037+00:00,Citroen Xsara Kit Car,0,Richard Burns Rally,1719840630,Race,...,1006.15900,0.0,-0.007843,0.000000,Dry Gravel,-231.150589,83.04983,-27.045351,-64.44776,1719840630-0
2,_result,1,2023-07-02 16:14:22.730341+00:00,2024-07-01 16:14:22.730341+00:00,2024-07-01 15:30:35.744887+00:00,Citroen Xsara Kit Car,0,Richard Burns Rally,1719840630,Race,...,1006.31830,0.0,-0.007843,0.000000,Dry Gravel,-231.150589,83.04983,-27.045351,-64.44776,1719840630-0
3,_result,1,2023-07-02 16:14:22.730341+00:00,2024-07-01 16:14:22.730341+00:00,2024-07-01 15:30:35.857103+00:00,Citroen Xsara Kit Car,0,Richard Burns Rally,1719840630,Race,...,1002.20752,0.0,-0.007843,0.007843,Dry Gravel,-231.150589,83.04983,-27.045351,-64.44776,1719840630-0
4,_result,1,2023-07-02 16:14:22.730341+00:00,2024-07-01 16:14:22.730341+00:00,2024-07-01 15:30:35.966476+00:00,Citroen Xsara Kit Car,0,Richard Burns Rally,1719840630,Race,...,1005.32544,0.0,-0.015686,0.168627,Dry Gravel,-231.150589,83.04983,-27.045351,-64.44776,1719840630-0

In [7]:
t.games().head()

,id,name,created,modified
0,1,iRacing,2023-07-04 16:27:23.231000+00:00,2023-07-04 16:27:23.240000+00:00
1,2,RaceRoom,2023-07-04 16:27:23.231000+00:00,2023-07-04 16:27:23.240000+00:00
2,3,Assetto Corsa Competizione,2023-07-04 16:27:23.231000+00:00,2023-07-04 16:27:23.240000+00:00
3,4,Assetto Corsa (64 bit),2023-07-04 16:27:23.231000+00:00,2023-07-04 16:27:23.240000+00:00
4,5,Automobilista 2,2023-07-04 16:27:23.231000+00:00,2023-07-04 16:27:23.240000+00:00

In [8]:
t.sessions().head()

,id,session_id,start,end,driver_id,game_id,session_type_id,created,modified
0,217034,1699005080,2023-11-03 10:51:20.663487+00:00,2023-11-03 10:51:21.098663+00:00,1,4,5,2023-11-03 10:51:21.150090+00:00,2023-11-03 10:51:21.150090+00:00
1,217094,1699008948,2023-11-03 11:55:49.837733+00:00,2023-11-03 13:01:19.491911+00:00,248,4,1,2023-11-03 11:55:49.923447+00:00,2023-11-03 13:01:19.495411+00:00
2,217058,1699006987,2023-11-03 11:22:18.131304+00:00,2023-11-03 11:32:51.623627+00:00,1,1,3,2023-11-03 11:22:20.214744+00:00,2023-11-03 11:32:51.635752+00:00
3,217035,1699005236,2023-11-03 10:53:56.204342+00:00,2023-11-03 10:53:56.423060+00:00,1,4,5,2023-11-03 10:53:56.493476+00:00,2023-11-03 10:53:56.493476+00:00
4,217032,1698994073,2023-11-03 10:47:44.521283+00:00,2023-11-03 10:56:56.860398+00:00,1,4,2,2023-11-03 10:47:45.667010+00:00,2023-11-03 10:56:56.885294+00:00